CREATE TABLE IF NOT EXISTS ods_product_daily_report (
    `日期`             Date,
    `产品名称`         String,
    `产品编号`         LowCardinality(String),
    `小组`             LowCardinality(String),
    `部门`             LowCardinality(String),
    `日活`             UInt64,
    `日活环比`         Float64,
    `总充值`           Float64,
    `总充值环比`       Float64,
    `自然充值`         Float64,
    `自然充值环比`     Float64,
    `渠道充值`         Float64,
    `渠道充值环比`     Float64,
    `内导充值`         Float64,
    `内导充值环比`     Float64,
    `总新增`           UInt64,
    `总新增环比`       Float64,
    `自然新增`         UInt64,
    `自然新增环比`     Float64,
    `渠道新增`         UInt64,
    `渠道新增环比`     Float64,
    `内导新增`         UInt64,
    `内导新增环比`     Float64,
    `新充人数`         UInt64,
    `老充人数`         UInt64,
    `新用户充值`       Float64,
    `老用户充值`       Float64,
    `充值单数`         UInt64,
    `付款成功率`       Float64,
    `次留率`           Float64,
    `3留率`            Float64,
    `7留率`            Float64,
    `下载页访问数`     UInt64,
    `下载页点击数`     UInt64,
    `落地页下载率`     Float64,
    `总转化`           Float64,
    `新充转化`         Float64,
    `老充转化`         Float64,
    `老用户日活`       UInt64,
    `ARPPU`            Float64,
    `_source`          LowCardinality(String) DEFAULT 'gsheet:测试-写入',
    `_src_row_no`      UInt32,
    `_ingested_at`     DateTime64(3) DEFAULT now64(),
    `_version`         UInt64 MATERIALIZED toUnixTimestamp64Milli(`_ingested_at`)
)
ENGINE = ReplacingMergeTree(`_version`)
PARTITION BY toYYYYMM(`日期`)
ORDER BY (`_source`, `日期`, `产品编号`)
SETTINGS index_granularity = 8192
