CREATE TABLE IF NOT EXISTS dws_product_daily (
    date                          Date,
    product_code                  LowCardinality(String),
    product_name                  String,
    team                          LowCardinality(String),
    business_unit                 LowCardinality(String),
    dau                           UInt64,
    dau_chain_ratio               Float64,
    old_user_dau                  UInt64,
    recharge_total_amt            Decimal(18, 2),
    recharge_total_chain_ratio    Float64,
    recharge_organic_amt          Decimal(18, 2),
    recharge_organic_chain_ratio  Float64,
    recharge_channel_amt          Decimal(18, 2),
    recharge_channel_chain_ratio  Float64,
    recharge_internal_amt         Decimal(18, 2),
    recharge_internal_chain_ratio Float64,
    new_user_total_cnt            UInt64,
    new_user_total_chain_ratio    Float64,
    new_user_organic_cnt          UInt64,
    new_user_organic_chain_ratio  Float64,
    new_user_channel_cnt          UInt64,
    new_user_channel_chain_ratio  Float64,
    new_user_internal_cnt         UInt64,
    new_user_internal_chain_ratio Float64,
    new_paying_user_cnt           UInt64,
    old_paying_user_cnt           UInt64,
    new_paying_user_amt           Decimal(18, 2),
    old_paying_user_amt           Decimal(18, 2),
    recharge_order_cnt            UInt64,
    payment_success_ratio         Float64,
    retention_d1_ratio            Float64,
    retention_d3_ratio            Float64,
    retention_d7_ratio            Float64,
    landing_page_visit_cnt        UInt64,
    landing_page_click_cnt        UInt64,
    landing_page_download_ratio   Float64,
    conversion_total_multi        Float64,
    conversion_new_paying_multi   Float64,
    conversion_old_paying_multi   Float64,
    arppu                         Decimal(18, 4),
    `_built_at`                   DateTime64(3) DEFAULT now64()
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(date)
ORDER BY (date, product_code)
